services:
  app:
    build: .
    volumes:
      - ./:/app
      - ./chromadb_wbc_usa:/app/chromadb_wbc_usa
      - ./path/to/ca-cert.pem:/app/ca-cert.pem   
    ports:
      - "5000:5000"
    environment:
      PORT: 5000
      CHANNEL_ACCESS_TOKEN: ${CHANNEL_ACCESS_TOKEN}
      CHANNEL_SECRET: ${CHANNEL_SECRET}
      GOOGLE_API_KEY: ${GOOGLE_API_KEY}
      DB_HOST: ${DB_HOST}     
      DB_PORT: 4000       
      DB_USER: ${DB_USER}
      DB_PASSWORD: ${DB_PASSWORD}
      DB_DATABASE: ${DB_DATABASE}
      DB_SSL_CA_PATH: /app/ca-cert.pem   
      DB_SSL_VERIFY_CERT: "True"   
      DB_SSL_VERIFY_IDENTITY: "True"    